= New Relic Jolokia Plugin - Java

A New Relic (NR) plugin agent for monitoring any service which expose JMX using jolokia, it uses jolokia endpoints to fetch metrics.

The NR dashboard for this plugin provides historical views of your instance's stats so you can easily see what went wrong and when.

This plugin allows you to easily receive alerts via NR.

== Requirements

- A New Relic account. Sign up for a free account http://newrelic.com[here]
- Java Runtime (JRE) environment Version 1.8+
- A Service exposing JMX with Jolokia

== Use Cases

We developed this plugin to monitoring an ActiveMQ Artemis instance, because it expose JMX using jolokia.
However, this plugin can be used for any service exposing JMX through jolokia.

== Installation

This plugin can be installed one of the following ways:

* Option 1 - New Relic Platform Installer
* Option 2 - Chef and Puppet Install Scripts
* Option 3 - Manual Install

=== Option 1 - Install with the New Relic Platform Installer

Once you've installed the NPI tool, run the following command:

```
npi install org.mule.newrelic.plugins.jolokia
```

=== Option 2 - Install via Chef or Puppet

New Relic has documentation for doing it with https://docs.newrelic.com/docs/plugins/plugins-new-relic/installing-plugins/plugin-installation-chef-and-puppet[Chef or Puppet].

=== Option 3 - Install Manually (Non-standard)

==== Step 1 - Downloading and Extracting the Plugin

The latest version of the plugin can be downloaded here. Once the plugin is on your box, extract it to a location of your choosing.

*Note:* This plugin is distributed in tar.gz format and can be extracted with the following command on Unix-based systems (Windows users will need to download a third-party extraction tool or use the New Relic Platform Installer):

```
tar -xvzf newrelic-jolokia-X.Y.Z.tar.gz
```

==== Step 2 - Configuring the Plugin

Check out the <<Configuration Information,configuration information>> section for details on configuring your plugin.

==== Step 3 - Running the Plugin

To run the plugin, execute the following command from a terminal or command window (assuming Java is installed and on your path):

```
java -Xmx128m -jar plugin.jar
```

*Note:* Though it is not necessary, the '-Xmx128m' flag is highly recommended due to the fact that when running the plugin on a server class machine, the java command will start a JVM that may reserve up to one quarter (25%) of available memory, but the '-Xmx128m' flag will limit heap allocation to a more reasonable 128MBs.

==== Step 4 - Keeping the Plugin Running

Step 3 showed you how to run the plugin; however, there are several problems with running the process directly in the foreground (For example, when the machine reboots the process will not be started again). That said, there are several common ways to keep a plugin running, but they do require more advanced knowledge or additional tooling. The recommended way is using the New Relic Platform Installer or Chef/Puppet scripts for installing plugins as they will take care of most of the heavy lifting for you.

If you prefer to be more involved in the maintaince of the process, consider one of these tools for managing your plugin process (bear in mind that some of these are OS-specific):

- http://upstart.ubuntu.com/[Upstart]
- http://www.freedesktop.org/wiki/Software/systemd/[Systemd]
- http://smarden.org/runit/[Runit]
- http://mmonit.com/monit/[Monit]

== Configuration Information

=== Custom Dashboard

* You *MUST* start the plugin using two system properties -Dplugin.name="organization.here" and -Dplugin.version="version.here", in order to setup custom dashboards and summary metrics.

_If you do not set these properties the default will be used, then it will appear with a default dashboard, which can't be edited and won't be presenting your JMX counters._

* Once you set your own plugin name and it reports in as a new plugin, you'll need to create dashboards and summary metrics to expose your Jolokia metrics. The New Relic Docs offer the best explanation of these capabilities

** https://docs.newrelic.com/docs/plugins/developing-plugins/structuring-your-plugin/changing-plugin-settings[Changing plugin settings]
** https://docs.newrelic.com/docs/plugins/developing-plugins/structuring-your-plugin/creating-summary-metrics-plugins[Creating summary metrics for plugins]
** https://docs.newrelic.com/docs/plugins/developing-plugins/structuring-your-plugin/working-plugin-dashboards[Working with plugin dashboards]

=== Configuration Files

You will need to modify two configuration files in order to set this plugin up to run. The first (```newrelic.json```) contains configurations used by all Platform plugins (e.g. license key, logging information, proxy settings) and can be shared across your plugins. The second (```plugin.json```) contains data specific to each plugin such as a list of hosts and port combination for what you are monitoring. Templates for both of these files should be located in the '```config```' directory in your extracted plugin folder.

=== Configuring the ```plugin.json``` file:

The ```plugin.json``` file has a provided template in the ```config``` directory named ```plugin.template.json```. If you are installing manually, make a copy of this template file and rename it to ```plugin.json``` (the New Relic Platform Installer will automatically handle creation of configuration files for you).

Below is an example of the ```plugin.json``` file's contents, you can add multiple objects to the "agents" array to monitor different instances:

```
{
  "agents": [
    {
      "name": "Instance Name",
      "host": "IP address of a jolokia server instance",
      "port": "8161"
      "metrics": [
        {
          "group_number": 1,
          "metric_name": "JVM/Threads/Count",
          "units": "threads",
          "object_name": "java.lang:type=Threading",
          "attribute_name": "ThreadCount",
          "jq_expression": ".value"
        }
      ]
    }
  ]
}
```

*Note:* You can modify this file in order to include different metrics.

=== Configuring the ```newrelic.json``` file:

The ```newrelic.json``` file also has a provided template in the ```config``` directory named ```newrelic.template.json```. If you are installing manually, make a copy of this template file and rename it to ```newrelic.json``` (again, the New Relic Platform Installer will automatically handle this for you).

The ```newrelic.json``` is a standardized file containing configuration information that applies to any plugin (e.g. license key, logging, proxy settings), so going forward you will be able to copy a single ```newrelic.json``` file from one plugin to another. Below is a list of the configuration fields that can be managed through this file:

Configuring your New Relic License Key
Your New Relic license key is the only required field in the ```newrelic.json``` file as it is used to determine what account you are reporting to. If you do not know what your license key is, you can learn about it here.

Example:

```
{
  "license_key": "YOUR_LICENSE_KEY_HERE"
}
```

=== Logging configuration

By default Platform plugins will have their logging turned on; however, you can manage these settings with the following configurations:

* ```log_level``` - The log level. Valid values: [```debug```, ```info```, ```warn```, ```error```, ```fatal```]. Defaults to ```info```.

* ```log_file_name``` - The log file name. Defaults to ```newrelic_plugin.log```.

* ```log_file_path``` - The log file path. Defaults to ```logs```.

* ```log_limit_in_kbytes``` - The log file limit in kilobytes. Defaults to ```25600``` (25 MB). If limit is set to ```0```, the log file size would not be limited.

Example:

```
{
  "license_key": "YOUR_LICENSE_KEY_HERE"
  "log_level": "debug",
  "log_file_path": "/var/logs/newrelic"
}
```

=== Proxy configuration

If you are running your plugin from a machine that runs outbound traffic through a proxy, you can use the following optional configurations in your ```newrelic.json``` file:

* ```proxy_host``` - The proxy host (e.g. ```webcache.example.com```)

* ```proxy_port``` - The proxy port (e.g. ```8080```). Defaults to ```80``` if a ```proxy_host``` is set

* ```proxy_username``` - The proxy username

* ```proxy_password``` - The proxy password

Example:

```
{
  "license_key": "YOUR_LICENSE_KEY_HERE",
  "proxy_host": "proxy.mycompany.com",
  "proxy_port": 9000
}
```

== Support

*Support is not guaranteed* - We are only able to provide support on a limited as time is available basis.

You can report any issue through https://github.com/mulesoft-labs/newrelic-plugins/issues[Github issue tracker]

== Frequently Asked Questions

*Q:* I've started this plugin, now what?

*A:* Once you have a plugin reporting with the proper license key, log into New Relic here. If everything was successful, you should see a new navigation item appear on the left navigation bar identifying your new plugin (This may take a few minutes). Click on this item to see the metrics for what you were monitoring (bear in mind, some details such as summary metrics may take several minutes to show values).

== Contributing

Pull requests welcome!